=== bviswana101/fetch-block/block_struct_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/object_17",
  "definitions": {
    "object_01": {
      "title": "chaincode_id",
      "type": "object",
      "required": [
        "name",
        "version"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "object_02": {
      "title": "channel_header",
      "type": "object",
      "required": [
        "type",
        "timestamp",
        "channel_id",
        "tx_id",
        "chaincode_id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "number"
        },
        "timestamp": {
          "title": "timestamp",
          "type": "object",
          "required": [
            "seconds",
            "nanos"
          ],
          "additionalProperties": false,
          "properties": {
            "seconds": {
              "type": "number"
            },
            "nanos": {
              "type": "number"
            }
          }
        },
        "channel_id": {
          "type": "string"
        },
        "tx_id": {
          "type": "string"
        },
        "chaincode_id": {
          "$ref": "#/definitions/object_01"
        }
      }
    },
    "object_03": {
      "title": "PublicKey",
      "type": "object",
      "required": [
        "Curve",
        "X",
        "Y"
      ],
      "additionalProperties": false,
      "properties": {
        "Curve": {
          "title": "Curve",
          "type": "object",
          "required": [
            "P",
            "N",
            "B",
            "Gx",
            "Gy",
            "BitSize",
            "Name"
          ],
          "additionalProperties": false,
          "properties": {
            "P": {
              "type": "number"
            },
            "N": {
              "type": "number"
            },
            "B": {
              "type": "number"
            },
            "Gx": {
              "type": "number"
            },
            "Gy": {
              "type": "number"
            },
            "BitSize": {
              "type": "number"
            },
            "Name": {
              "type": "string"
            }
          }
        },
        "X": {
          "type": "number"
        },
        "Y": {
          "type": "number"
        }
      }
    },
    "object_04": {
      "type": "object",
      "required": [
        "Type",
        "Value"
      ],
      "additionalProperties": false,
      "properties": {
        "Type": {
          "$ref": "#/definitions/array_02"
        },
        "Value": {
          "type": "string"
        }
      }
    },
    "object_05": {
      "type": "object",
      "required": [
        "Country",
        "Organization",
        "OrganizationalUnit",
        "Locality",
        "Province",
        "StreetAddress",
        "PostalCode",
        "SerialNumber",
        "CommonName",
        "Names",
        "ExtraNames"
      ],
      "additionalProperties": false,
      "properties": {
        "Country": {
          "$ref": "#/definitions/array_01"
        },
        "Organization": {
          "$ref": "#/definitions/array_01"
        },
        "OrganizationalUnit": {
          "$ref": "#/definitions/array_01"
        },
        "Locality": {
          "$ref": "#/definitions/array_01"
        },
        "Province": {
          "$ref": "#/definitions/array_01"
        },
        "StreetAddress": {
          "type": "null"
        },
        "PostalCode": {
          "type": "null"
        },
        "SerialNumber": {
          "type": "string"
        },
        "CommonName": {
          "type": "string"
        },
        "Names": {
          "anyOf": [
            {
              "$ref": "#/definitions/array_03"
            },
            {
              "$ref": "#/definitions/array_04"
            }
          ]
        },
        "ExtraNames": {
          "type": "null"
        }
      }
    },
    "object_06": {
      "type": "object",
      "required": [
        "Id",
        "Critical",
        "Value"
      ],
      "additionalProperties": false,
      "properties": {
        "Id": {
          "$ref": "#/definitions/array_02"
        },
        "Critical": {
          "type": "boolean"
        },
        "Value": {
          "type": "string"
        }
      }
    },
    "object_07": {
      "title": "Certificate",
      "type": "object",
      "required": [
        "Raw",
        "RawTBSCertificate",
        "RawSubjectPublicKeyInfo",
        "RawSubject",
        "RawIssuer",
        "Signature",
        "SignatureAlgorithm",
        "PublicKeyAlgorithm",
        "PublicKey",
        "Version",
        "SerialNumber",
        "Issuer",
        "Subject",
        "NotBefore",
        "NotAfter",
        "KeyUsage",
        "Extensions",
        "ExtraExtensions",
        "UnhandledCriticalExtensions",
        "ExtKeyUsage",
        "UnknownExtKeyUsage",
        "BasicConstraintsValid",
        "IsCA",
        "MaxPathLen",
        "MaxPathLenZero",
        "SubjectKeyId",
        "AuthorityKeyId",
        "OCSPServer",
        "IssuingCertificateURL",
        "DNSNames",
        "EmailAddresses",
        "IPAddresses",
        "PermittedDNSDomainsCritical",
        "PermittedDNSDomains",
        "CRLDistributionPoints",
        "PolicyIdentifiers"
      ],
      "additionalProperties": false,
      "properties": {
        "Raw": {
          "type": "string"
        },
        "RawTBSCertificate": {
          "type": "string"
        },
        "RawSubjectPublicKeyInfo": {
          "type": "string"
        },
        "RawSubject": {
          "type": "string"
        },
        "RawIssuer": {
          "type": "string"
        },
        "Signature": {
          "type": "string"
        },
        "SignatureAlgorithm": {
          "type": "number"
        },
        "PublicKeyAlgorithm": {
          "type": "number"
        },
        "PublicKey": {
          "$ref": "#/definitions/object_03"
        },
        "Version": {
          "type": "number"
        },
        "SerialNumber": {
          "type": "number"
        },
        "Issuer": {
          "$ref": "#/definitions/object_05"
        },
        "Subject": {
          "$ref": "#/definitions/object_05"
        },
        "NotBefore": {
          "type": "string",
          "format": "date-time"
        },
        "NotAfter": {
          "type": "string",
          "format": "date-time"
        },
        "KeyUsage": {
          "type": "number"
        },
        "Extensions": {
          "$ref": "#/definitions/array_05"
        },
        "ExtraExtensions": {
          "type": "null"
        },
        "UnhandledCriticalExtensions": {
          "type": "null"
        },
        "ExtKeyUsage": {
          "$ref": "#/definitions/array_06"
        },
        "UnknownExtKeyUsage": {
          "type": "null"
        },
        "BasicConstraintsValid": {
          "type": "boolean"
        },
        "IsCA": {
          "type": "boolean"
        },
        "MaxPathLen": {
          "type": "number"
        },
        "MaxPathLenZero": {
          "type": "boolean"
        },
        "SubjectKeyId": {
          "type": "string"
        },
        "AuthorityKeyId": {
          "type": "string"
        },
        "OCSPServer": {
          "type": "null"
        },
        "IssuingCertificateURL": {
          "type": "null"
        },
        "DNSNames": {
          "$ref": "#/definitions/array_07"
        },
        "EmailAddresses": {
          "type": "null"
        },
        "IPAddresses": {
          "type": "null"
        },
        "PermittedDNSDomainsCritical": {
          "type": "boolean"
        },
        "PermittedDNSDomains": {
          "type": "null"
        },
        "CRLDistributionPoints": {
          "type": "null"
        },
        "PolicyIdentifiers": {
          "type": "null"
        }
      }
    },
    "object_08": {
      "type": "object",
      "required": [
        "Certificate",
        "nonce"
      ],
      "additionalProperties": false,
      "properties": {
        "Certificate": {
          "anyOf": [
            {
              "$ref": "#/definitions/object_07"
            },
            {
              "type": "null"
            }
          ]
        },
        "nonce": {
          "type": "string"
        }
      }
    },
    "object_09": {
      "title": "input",
      "type": "object",
      "required": [
        "Args"
      ],
      "additionalProperties": false,
      "properties": {
        "Args": {
          "$ref": "#/definitions/array_01"
        }
      }
    },
    "object_10": {
      "title": "chaincode_spec",
      "type": "object",
      "required": [
        "type",
        "chaincode_id",
        "input"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "number"
        },
        "chaincode_id": {
          "$ref": "#/definitions/object_01"
        },
        "input": {
          "$ref": "#/definitions/object_09"
        }
      }
    },
    "object_11": {
      "type": "object",
      "additionalProperties": false,
      "properties": {}
    },
    "object_12": {
      "type": "object",
      "required": [
        "key",
        "version"
      ],
      "additionalProperties": false,
      "properties": {
        "key": {
          "type": "string"
        },
        "version": {
          "title": "version",
          "type": "object",
          "required": [
            "block_num"
          ],
          "additionalProperties": false,
          "properties": {
            "block_num": {
              "type": "number"
            }
          }
        }
      }
    },
    "object_13": {
      "type": "object",
      "required": [
        "Namespace",
        "KVRWSet"
      ],
      "additionalProperties": false,
      "properties": {
        "Namespace": {
          "type": "string"
        },
        "KVRWSet": {
          "$ref": "#/definitions/object_14"
        }
      }
    },
    "object_14": {
      "title": "KVRWSet",
      "type": "object",
      "required": [
        "reads"
      ],
      "additionalProperties": false,
      "properties": {
        "reads": {
          "type": "array",
          "title": "reads",
          "items": {
            "$ref": "#/definitions/object_12"
          }
        },
        "writes": {
          "type": "array",
          "title": "writes",
          "items": {
            "type": "object",
            "required": [
              "key",
              "value"
            ],
            "additionalProperties": false,
            "properties": {
              "key": {
                "type": "string"
              },
              "value": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "object_15": {
      "type": "object",
      "required": [
        "signature",
        "signature_header"
      ],
      "additionalProperties": false,
      "properties": {
        "signature": {
          "type": "string"
        },
        "channel_header": {
          "$ref": "#/definitions/object_02"
        },
        "signature_header": {
          "$ref": "#/definitions/object_08"
        },
        "tx_action_signature_header": {
          "$ref": "#/definitions/object_08"
        },
        "chaincode_spec": {
          "$ref": "#/definitions/object_10"
        },
        "endorsements": {
          "$ref": "#/definitions/array_08"
        },
        "proposal_hash": {
          "type": "string"
        },
        "events": {
          "$ref": "#/definitions/object_11"
        },
        "response": {
          "title": "response",
          "type": "object",
          "required": [
            "status",
            "payload"
          ],
          "additionalProperties": false,
          "properties": {
            "status": {
              "type": "number"
            },
            "payload": {
              "type": "string"
            }
          }
        },
        "ns_read_write_Set": {
          "type": "array",
          "title": "ns_read_write_Set",
          "items": {
            "$ref": "#/definitions/object_13"
          }
        },
        "validation_code": {
          "type": "number"
        }
      }
    },
    "object_16": {
      "title": "last_config_block_number",
      "type": "object",
      "required": [
        "last_config_block_num",
        "signature_data"
      ],
      "additionalProperties": false,
      "properties": {
        "last_config_block_num": {
          "type": "number"
        },
        "signature_data": {
          "$ref": "#/definitions/object_15"
        }
      }
    },
    "object_17": {
      "type": "object",
      "required": [
        "header",
        "transactions",
        "block_creator_signature",
        "last_config_block_number",
        "orderer_kafka_metadata"
      ],
      "additionalProperties": false,
      "properties": {
        "header": {
          "title": "header",
          "type": "object",
          "required": [
            "number",
            "previous_hash",
            "data_hash"
          ],
          "additionalProperties": false,
          "properties": {
            "number": {
              "type": "number"
            },
            "previous_hash": {
              "type": "string"
            },
            "data_hash": {
              "type": "string"
            }
          }
        },
        "transactions": {
          "$ref": "#/definitions/array_08"
        },
        "block_creator_signature": {
          "$ref": "#/definitions/object_15"
        },
        "last_config_block_number": {
          "$ref": "#/definitions/object_16"
        },
        "orderer_kafka_metadata": {
          "$ref": "#/definitions/object_11"
        }
      }
    },
    "array_01": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "array_02": {
      "type": "array",
      "title": "Type, Id",
      "description": "tuple type",
      "additionalItems": false,
      "minItems": 4,
      "maxItems": 4,
      "items": [
        {
          "type": "number"
        },
        {
          "type": "number"
        },
        {
          "type": "number"
        },
        {
          "type": "number"
        }
      ]
    },
    "array_03": {
      "type": "array",
      "title": "Names",
      "description": "tuple type",
      "additionalItems": false,
      "minItems": 6,
      "maxItems": 6,
      "items": [
        {
          "$ref": "#/definitions/object_04"
        },
        {
          "$ref": "#/definitions/object_04"
        },
        {
          "$ref": "#/definitions/object_04"
        },
        {
          "$ref": "#/definitions/object_04"
        },
        {
          "$ref": "#/definitions/object_04"
        },
        {
          "$ref": "#/definitions/object_04"
        }
      ]
    },
    "array_04": {
      "type": "array",
      "title": "Names",
      "description": "tuple type",
      "additionalItems": false,
      "minItems": 5,
      "maxItems": 5,
      "items": [
        {
          "$ref": "#/definitions/object_04"
        },
        {
          "$ref": "#/definitions/object_04"
        },
        {
          "$ref": "#/definitions/object_04"
        },
        {
          "$ref": "#/definitions/object_04"
        },
        {
          "$ref": "#/definitions/object_04"
        }
      ]
    },
    "array_05": {
      "type": "array",
      "title": "Extensions",
      "description": "tuple type",
      "additionalItems": false,
      "minItems": 6,
      "maxItems": 6,
      "items": [
        {
          "$ref": "#/definitions/object_06"
        },
        {
          "$ref": "#/definitions/object_06"
        },
        {
          "$ref": "#/definitions/object_06"
        },
        {
          "$ref": "#/definitions/object_06"
        },
        {
          "$ref": "#/definitions/object_06"
        },
        {
          "$ref": "#/definitions/object_06"
        }
      ]
    },
    "array_06": {
      "type": "array",
      "title": "ExtKeyUsage",
      "description": "tuple type",
      "additionalItems": false,
      "minItems": 2,
      "maxItems": 2,
      "items": [
        {
          "type": "number"
        },
        {
          "type": "number"
        }
      ]
    },
    "array_07": {
      "type": "array",
      "title": "DNSNames",
      "description": "tuple type",
      "additionalItems": false,
      "minItems": 2,
      "maxItems": 2,
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "array_08": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/object_15"
      }
    }
  }
}

=== bviswana101/fetch-block/sample_block_json/ch1_blk#6.json
{
  "header": {
    "number": 6,
    "previous_hash": "j7883yWIgQJhG6sICj6nma/fYeJS1CY4wZKZx4U0+B8=",
    "data_hash": "rvmwmM9tzKoPOoWqbwiZlAXTcYUdUigoVC+4WDsbXWg="
  },
  "transactions": [
    {
      "signature": "MEQCIAKcLtI4Z+MHco+muVUxXnlF49lgmQcHDybxElyaHAPFAiAu3qdvLEakbyduhOz6gm54jVGydIrqDNJBopOxWh6WjA==",
      "channel_header": {
        "type": 3,
        "timestamp": {
          "seconds": 1494408478,
          "nanos": 82512480
        },
        "channel_id": "ch1",
        "tx_id": "dd45daabe210430c5dc59eaa2fb1adefaeb18cc4001b24500acc1e60af22c730",
        "chaincode_id": {
          "name": "mycc1",
          "version": "0"
        }
      },
      "signature_header": {
        "Certificate": {
          "Raw": "MIICizCCAjKgAwIBAgIUBEVwsSx0TmqdbzNwleNBBzoIT0wwCgYIKoZIzj0EAwIwfzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xHzAdBgNVBAoTFkludGVybmV0IFdpZGdldHMsIEluYy4xDDAKBgNVBAsTA1dXVzEUMBIGA1UEAxMLZXhhbXBsZS5jb20wHhcNMTYxMTExMTcwNzAwWhcNMTcxMTExMTcwNzAwWjBjMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExEDAOBgNVBAcTB1JhbGVpZ2gxGzAZBgNVBAoTEkh5cGVybGVkZ2VyIEZhYnJpYzEMMAoGA1UECxMDQ09QMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHBuKsAO43hs4JGpFfiGMkB/xsILTsOvmN2WmwpsPHZNL6w8HWe3xCPQtdG/XJJvZ+C756KEsUBM3yw5PTfku8qOBpzCBpDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFOFCdcUZ4es3ltiCgAVDoyLfVpPIMB8GA1UdIwQYMBaAFBdnQj2qnoI/xMUdn1vDmdG1nEgQMCUGA1UdEQQeMByCCm15aG9zdC5jb22CDnd3dy5teWhvc3QuY29tMAoGCCqGSM49BAMCA0cAMEQCIDf9Hbl4xn3z4EwNKmilM9lX2Fq4jWpAaRVB97OmVEeyAiAkaXzB/jnlU39B7Wws9BIr9c8mSOEPF6VY1uGP+dKV0g==",
          "RawTBSCertificate": "MIICMqADAgECAhQERXCxLHROap1vM3CV40EHOghPTDAKBggqhkjOPQQDAjB/MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEfMB0GA1UEChMWSW50ZXJuZXQgV2lkZ2V0cywgSW5jLjEMMAoGA1UECxMDV1dXMRQwEgYDVQQDEwtleGFtcGxlLmNvbTAeFw0xNjExMTExNzA3MDBaFw0xNzExMTExNzA3MDBaMGMxCzAJBgNVBAYTAlVTMRcwFQYDVQQIEw5Ob3J0aCBDYXJvbGluYTEQMA4GA1UEBxMHUmFsZWlnaDEbMBkGA1UEChMSSHlwZXJsZWRnZXIgRmFicmljMQwwCgYDVQQLEwNDT1AwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQcG4qwA7jeGzgkakV+IYyQH/GwgtOw6+Y3ZabCmw8dk0vrDwdZ7fEI9C10b9ckm9n4LvnooSxQEzfLDk9N+S7yo4GnMIGkMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU4UJ1xRnh6zeW2IKABUOjIt9Wk8gwHwYDVR0jBBgwFoAUF2dCPaqegj/ExR2fW8OZ0bWcSBAwJQYDVR0RBB4wHIIKbXlob3N0LmNvbYIOd3d3Lm15aG9zdC5jb20=",
          "RawSubjectPublicKeyInfo": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHBuKsAO43hs4JGpFfiGMkB/xsILTsOvmN2WmwpsPHZNL6w8HWe3xCPQtdG/XJJvZ+C756KEsUBM3yw5PTfku8g==",
          "RawSubject": "MGMxCzAJBgNVBAYTAlVTMRcwFQYDVQQIEw5Ob3J0aCBDYXJvbGluYTEQMA4GA1UEBxMHUmFsZWlnaDEbMBkGA1UEChMSSHlwZXJsZWRnZXIgRmFicmljMQwwCgYDVQQLEwNDT1A=",
          "RawIssuer": "MH8xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMR8wHQYDVQQKExZJbnRlcm5ldCBXaWRnZXRzLCBJbmMuMQwwCgYDVQQLEwNXV1cxFDASBgNVBAMTC2V4YW1wbGUuY29t",
          "Signature": "MEQCIDf9Hbl4xn3z4EwNKmilM9lX2Fq4jWpAaRVB97OmVEeyAiAkaXzB/jnlU39B7Wws9BIr9c8mSOEPF6VY1uGP+dKV0g==",
          "SignatureAlgorithm": 10,
          "PublicKeyAlgorithm": 3,
          "PublicKey": {
            "Curve": {
              "P": 115792089210356248762697446949407573530086143415290314195533631308867097853951,
              "N": 115792089210356248762697446949407573529996955224135760342422259061068512044369,
              "B": 41058363725152142129326129780047268409114441015993725554835256314039467401291,
              "Gx": 48439561293906451759052585252797914202762949526041747995844080717082404635286,
              "Gy": 36134250956749795798585127919587881956611106672985015071877198253568414405109,
              "BitSize": 256,
              "Name": "P-256"
            },
            "X": 12713421817418932763413718645318291131658429549618161805148108180370161081747,
            "Y": 34338776428353405405758244684264567987888272761951209233206748157655345868530
          },
          "Version": 3,
          "SerialNumber": 24384531367087201972415224946499269301170097996,
          "Issuer": {
            "Country": [
              "US"
            ],
            "Organization": [
              "Internet Widgets, Inc."
            ],
            "OrganizationalUnit": [
              "WWW"
            ],
            "Locality": [
              "San Francisco"
            ],
            "Province": [
              "California"
            ],
            "StreetAddress": null,
            "PostalCode": null,
            "SerialNumber": "",
            "CommonName": "example.com",
            "Names": [
              {
                "Type": [
                  2,
                  5,
                  4,
                  6
                ],
                "Value": "US"
              },
              {
                "Type": [
                  2,
                  5,
                  4,
                  8
                ],
                "Value": "California"
              },
              {
                "Type": [
                  2,
                  5,
                  4,
                  7
                ],
                "Value": "San Francisco"
              },
              {
                "Type": [
                  2,
                  5,
                  4,
                  10
                ],
                "Value": "Internet Widgets, Inc."
              },
              {
                "Type": [
                  2,
                  5,
                  4,
                  11
                ],
                "Value": "WWW"
              },
              {
                "Type": [
                  2,
                  5,
                  4,
                  3
                ],
                "Value": "example.com"
              }
            ],
            "ExtraNames": null
          },
          "Subject": {
            "Country": [
              "US"
            ],
            "Organization": [
              "Hyperledger Fabric"
            ],
            "OrganizationalUnit": [
              "COP"
            ],
            "Locality": [
              "Raleigh"
            ],
            "Province": [
              "North Carolina"
            ],
            "StreetAddress": null,
            "PostalCode": null,
            "SerialNumber": "",
            "CommonName": "",
            "Names": [
              {
                "Type": [
                  2,
                  5,
                  4,
                  6
                ],
                "Value": "US"
              },
              {
                "Type": [
                  2,
                  5,
                  4,
                  8
                ],
                "Value": "North Carolina"
              },
              {
                "Type": [
                  2,
                  5,
                  4,
                  7
                ],
                "Value": "Raleigh"
              },
              {
                "Type": [
                  2,
                  5,
                  4,
                  10
                ],
                "Value": "Hyperledger Fabric"
              },
              {
                "Type": [
                  2,
                  5,
                  4,
                  11
                ],
                "Value": "COP"
              }
            ],
            "ExtraNames": null
          },
          "NotBefore": "2016-11-11T17:07:00Z",
          "NotAfter": "2017-11-11T17:07:00Z",
          "KeyUsage": 5,
          "Extensions": [
            {
              "Id": [
                2,
                5,
                29,
                15
              ],
              "Critical": true,
              "Value": "AwIFoA=="
            },
            {
              "Id": [
                2,
                5,
                29,
                37
              ],
              "Critical": false,
              "Value": "MBQGCCsGAQUFBwMBBggrBgEFBQcDAg=="
            },
            {
              "Id": [
                2,
                5,
                29,
                19
              ],
              "Critical": true,
              "Value": "MAA="
            },
            {
              "Id": [
                2,
                5,
                29,
                14
              ],
              "Critical": false,
              "Value": "BBThQnXFGeHrN5bYgoAFQ6Mi31aTyA=="
            },
            {
              "Id": [
                2,
                5,
                29,
                35
              ],
              "Critical": false,
              "Value": "MBaAFBdnQj2qnoI/xMUdn1vDmdG1nEgQ"
            },
            {
              "Id": [
                2,
                5,
                29,
                17
              ],
              "Critical": false,
              "Value": "MByCCm15aG9zdC5jb22CDnd3dy5teWhvc3QuY29t"
            }
          ],
          "ExtraExtensions": null,
          "UnhandledCriticalExtensions": null,
          "ExtKeyUsage": [
            1,
            2
          ],
          "UnknownExtKeyUsage": null,
          "BasicConstraintsValid": true,
          "IsCA": false,
          "MaxPathLen": -1,
          "MaxPathLenZero": false,
          "SubjectKeyId": "4UJ1xRnh6zeW2IKABUOjIt9Wk8g=",
          "AuthorityKeyId": "F2dCPaqegj/ExR2fW8OZ0bWcSBA=",
          "OCSPServer": null,
          "IssuingCertificateURL": null,
          "DNSNames": [
            "myhost.com",
            "www.myhost.com"
          ],
          "EmailAddresses": null,
          "IPAddresses": null,
          "PermittedDNSDomainsCritical": false,
          "PermittedDNSDomains": null,
          "CRLDistributionPoints": null,
          "PolicyIdentifiers": null
        },
        "nonce": "P1te+7havgFJXCqcr0r7e8Eexc73iSo7"
      },
      "tx_action_signature_header": {
        "Certificate": {
